[book]
title = "计算机网络：自顶向下方法（第8版）- 笔记"
authors = ["PrettyC"]
description = "计算机网络：自顶向下方法（第8版）读书笔记"
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true

[preprocessor.plantuml]
plantuml-cmd = "plantuml"
#command = "mdbook-plantuml -l"  # This enables debug logging and creates a file output.txt
clickable-img = false
use-data-uris = true
piped = true

[preprocessor.katex]
after = ["links"]